services:
  - type: web
    name: clothes-organiser-api
    env: node
    plan: free
    region: oregon
    buildCommand: npm ci
    startCommand: node server/index.js
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: static_site
    name: clothes-organiser-web
    plan: free
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    autoDeploy: true
    envVars:
      # Set this to your API's external URL + /api. Adjust if your API host differs.
      - key: VITE_API_URL
        value: https://clothes-organiser-api.onrender.com/api
